### ISSUE TITLE
TestController 的第二个方法，测试事务消息失败

### ISSUE THREAD

**Issue by wangxiaowei1997** [qq54903099/spring-cloud-demo#1]
TestController 的第二个方法，测试事务消息失败。在抛出异常的情况下，依然可以看到消费者消费的日志。
解决方法:

在RabbitConfiguration中指定事务管理器  取代Spring默认的事务管理器

    @Bean("rabbitTransactionManager")
    public RabbitTransactionManager rabbitTransactionManager(CachingConnectionFactory connectionFactory) {
        return new RabbitTransactionManager(connectionFactory);
    }

**Comment by liangliang4ward** [comment]
感谢提出问题，已经修复
